/**
 * @file Single card display object.
 *
 * Each card is a **Sprite** backed by a pre-baked RenderTexture generated by
 * AceOfShadowsScene at startup.  All text (value + suit labels, watermark) is
 * baked into the texture, so this view is a zero-overhead Sprite with no live
 * text children.
 *
 * This satisfies the spec requirement: *"Create 144 sprites (NOT graphic objects)"*.
 */

import { Sprite, Texture } from 'pixi.js';
import type { CardModel } from '../models/CardModel';
import { CARD_W, CARD_H } from '../constants';

export class CardView extends Sprite {
  public readonly model: CardModel;

  public constructor(model: CardModel, texture: Texture) {
    super(texture);
    this.model = model;
    this.width  = CARD_W;
    this.height = CARD_H;
    // Centre anchor so rotation/scale during flight pivot around the card centre.
    this.anchor.set(0.5);
  }
}
